# Generated by Django 4.0.3 on 2022-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.FileField(default='avtar.png', null=True, upload_to='shoesimg'),
        ),
    ]
