# Generated by Django 4.0.2 on 2022-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_catagory_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=200)),
                ('enq_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
