# Generated by Django 4.0.3 on 2022-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50, null=True)),
                ('Lname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('address', models.TextField(null=True)),
                ('pic', models.FileField(default='avtar.png', null=True, upload_to='Profile Pic')),
            ],
        ),
    ]
