# Generated by Django 4.0.3 on 2022-04-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Lname',
            new_name='lname',
        ),
    ]
