# Generated by Django 4.0.3 on 2022-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
